# Generated by Django 4.1.5 on 2023-01-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.address')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=50)),
                ('landline_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ageRating', models.PositiveSmallIntegerField()),
                ('duration', models.DurationField()),
                ('shortTrailerDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('S', 'Student'), ('A', 'Adult'), ('C', 'Child')], default='S', max_length=1)),
                ('ticket_price', models.CharField(choices=[('S', '10'), ('A', '15'), ('C', '5')], max_length=1)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.showing')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.account')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('club_representatice_number', models.IntegerField(unique=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubRep', to='UWEFlix.club')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='contact_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.contactdetails'),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.booking')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.club'),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.paymentdetails'),
        ),
    ]
