# Generated by Django 4.1.5 on 2023-01-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_rename_club_representatice_number_clubrepresentative_club_representative_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='ageRating',
            new_name='age_rating',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='shortTrailerDescription',
            new_name='short_trailer_description',
        ),
    ]
