# Generated by Django 4.1.5 on 2023-01-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_alter_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
