# Generated by Django 4.1.5 on 2023-01-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_alter_screen_screen_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
