# Generated by Django 4.1.5 on 2023-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0006_clubrepresentative_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrepresentative',
            name='club_representative_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
