# Generated by Django 4.1.5 on 2023-01-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0007_alter_clubrepresentative_club_representative_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UWEFlix.showing'),
        ),
    ]
