# Generated by Django 4.1.5 on 2023-01-15 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWEFlix', '0008_booking_showing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubrepresentative',
            options={},
        ),
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='password',
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
